import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: "#faf9f7",
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1a1a1a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#0057ff",
    borderBottomStyle: "solid",
  },
  name: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
    letterSpacing: -0.5,
  },
  title: {
    fontSize: 9,
    color: "#6b6b6b",
    marginTop: 4,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  contactBlock: {
    alignItems: "flex-end",
  },
  contactItem: {
    fontSize: 8,
    color: "#6b6b6b",
    marginBottom: 2,
  },
  sectionLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#0057ff",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: 16,
  },
  bodyText: {
    fontSize: 9.5,
    color: "#3a3a3a",
    lineHeight: 1.55,
    marginBottom: 12,
  },
  divider: {
    height: 1,
    backgroundColor: "#f0eee9",
    marginVertical: 12,
  },
  highlightsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 12,
  },
  chip: {
    backgroundColor: "#e8f0ff",
    color: "#0057ff",
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    padding: "3 8",
    borderRadius: 3,
  },
  toolChip: {
    backgroundColor: "#fce8f3",
    color: "#e0007a",
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    padding: "3 8",
    borderRadius: 3,
  },
  projectCard: {
    backgroundColor: "#ffffff",
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#f0eee9",
    borderStyle: "solid",
  },
  projectTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  projectRole: {
    fontSize: 8,
    color: "#6b6b6b",
    marginBottom: 3,
  },
  projectDesc: {
    fontSize: 8.5,
    color: "#3a3a3a",
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 7,
    color: "#aaaaaa",
    letterSpacing: 0.5,
  },
  accentBar: {
    height: 2,
    backgroundColor: "#0057ff",
    marginBottom: 6,
    borderRadius: 9999,
  },
});
